vich_uploader:
    db_driver: orm

    mappings:
        city_images:
            uri_prefix: '%app.path.city_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.city_images%'
        hotel_images:
            uri_prefix: '%app.path.hotel_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.hotel_images%'
        hotel_gallery:
            uri_prefix: '/images/hotel/gallery'
            upload_destination: '%kernel.project_dir%/public/images/hotel/gallery'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

